## These functions are able to cache the inverse of a matrix. Since it can be a time consuming 
## operation it can be handy to store a value, so that you are able to retrieve it when needed
## and do not need to calculate it again.

## makeCacheMatrix is a functions that return a lsit of functions. 
## The function set is used to specify the matrix of which the inverse will be (or is) calculated
## The function get is used to retrieve the matrix of which the inverse will be (or is) calculated
## The function setinverse is used to set a value to m
## The function getinverse is used to retrieve the object m

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) m <<- inverse
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

x <- makeCacheMatrix() # this line of code needed for the second function to work, 
                       # since the cacheSolve is using the list generated by 
                       # the makeCacheMatrix function.

## This function calculates the inverse of the matrix specified in the makeCacheMatrix,
## but it checks first if it has already been calculated. If this is the case it will
## retrieve the value calculated previously. If this is not the cases, it will calculate
## the inverse of the matrix and store it the the cache. It it wise to always to check of which
## matrix the inverse has been calculated with the get function of the makeCacheVector function.
## This is to ensure that the inverse corresponds to the matrix you want, since if a inverse has
## it will print out the inverse, without specifying for wich matrix it was calculated.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
        ## Returns a matrix that is the inverse of 'x'
}
